// Code generated by "stringer -type ShapeFlags render.go"; DO NOT EDIT.

package sys

import "strconv"

const (
	_ShapeFlags_name_0 = "None"
	_ShapeFlags_name_1 = "Default"
	_ShapeFlags_name_2 = "SkipInBulk"
)

func (i ShapeFlags) String() string {
	switch {
	case i == 0:
		return _ShapeFlags_name_0
	case i == 2:
		return _ShapeFlags_name_1
	case i == 4:
		return _ShapeFlags_name_2
	default:
		return "ShapeFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
